FROM pytorch/pytorch:2.7.1-cuda12.8-cudnn9-runtime


# specify vscode as the user name in the docker
# This user name should match that of the VS Code .devcontainer to allow seamless development inside the docker container via vscode 
ARG USERNAME=vscode
ARG USER_UID=1001
ARG USER_GID=$USER_UID

# Create a non-root user
RUN groupadd --gid $USER_GID $USERNAME \
  && useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME \
  # [Optional] Add sudo support for the non-root user - this is ok for development dockers only
  && apt-get update \
  && apt-get install -y sudo \
  && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME\
  && chmod 0440 /etc/sudoers.d/$USERNAME \
  # Cleanup
  && rm -rf /var/lib/apt/lists/* \
  # Set up git completion.
  && echo "source /usr/share/bash-completion/completions/git" >> /home/$USERNAME/.bashrc 


# Packages installation (eg git-lfs)
RUN sed -i 's/htt[p|ps]:\/\/archive.ubuntu.com\/ubuntu\//mirror:\/\/mirrors.ubuntu.com\/mirrors.txt/g' /etc/apt/sources.list
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
     && apt-get -y install --no-install-recommends curl git-lfs ffmpeg make bash-completion  python3-venv openssh-client \
     && rm -rf /var/cache/apt && \
     apt-get clean
# && apt-get -y install --no-install-recommends libsm6 libxext6 graphviz libgraphviz-dev xdg-utils swig gringo gobject-introspection libcairo2-dev libgirepository1.0-dev pkg-config python3-dev python3-gi

# Install uv for modern Python package management
COPY --from=ghcr.io/astral-sh/uv:latest --chown=vscode: /uv /uvx /bin/

# Copy the constraint file - we respect the existing package versions
RUN mkdir -p /etc/pip
RUN pip list --format=freeze > /etc/pip/constraint.txt
# This is a workaround to avoid issues with fsspec version 2025.5.1 as it conflicts with HF datasets 3.6.0
RUN sed -i 's/^fsspec==2025\.5\.1$/fsspec==2025.3.0/' /etc/pip/constraint.txt


# Install Node.js (required for some Quarto extensions)
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y nodejs

# Quarto
RUN curl -LO https://quarto.org/download/latest/quarto-linux-amd64.deb && \
    dpkg -i quarto-linux-amd64.deb
#RUN quarto install tinytex

RUN curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --dearmor > /usr/share/keyrings/1password-archive-keyring.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main" > /etc/apt/sources.list.d/1password.list \
    && apt update \
    && apt install -y 1password-cli

USER vscode

# Disable GPG signing for git commits
RUN git config --global commit.gpgsign false

